### ISSUE TITLE
console/chat gets spammed

### ISSUE THREAD

**Issue by saybrook** [k0rd/Custom-Monsters-Plugin--Tshock-#15]
the console and game is being spammed with spawning messages either

baename:mobname

or

spawnmessage:

depending on the config file.

this should be something that can be turned off by removing the spawnmessage config item

**Comment by k0rd** [comment]
yes. this is intentional. these options no longer exist... a spawn message is created like this..

name:fakemob
option:whatever
option:whatever
this is the spawn messeage!!!
