### ISSUE TITLE
multiplyondeath is currently not working

### ISSUE THREAD

**Issue by Pychnight** [k0rd/Custom-Monsters-Plugin--Tshock-#3]
this is still broken.

**Comment by Olink** [comment]
Could you provide a config that "should" multiply on death? I am new to the project and dont even want to try playing with configs.

**Comment by Pychnight** [comment]
name:MultiplyonDeath
basetype:-4
life:300
value:1000
forest:250
shooterdata:84:1:10:5
multiplyondeath:5

**Comment by Olink** [comment]
fixed
